import streamlit as st
import math
from PIL import Image, ImageDraw
import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfgen import canvas
from io import BytesIO
import re

# =============================================================
# PDF helpers: footer + settings-driven options
# =============================================================
def _add_footer(c, doc):
    footer_text = st.session_state.get("settings", {}).get(
        "footer_text", "Generated by Title 5 Plan Reader v1.0 — © 2025 [Your Organization]"
    )
    c.saveState()
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(40, 25, footer_text)
    c.restoreState()

# =============================================================
# Sidebar: ⚙️ Settings (persistent)
# =============================================================
with st.sidebar:
    st.markdown("### ⚙️ Settings")

    if "settings" not in st.session_state:
        st.session_state["settings"] = {
            "dpi": 300,
            "min_text_len": 3,
            "manual_ltar": False,
            "default_ltar": 1.0,
            "include_thumbs": True,
            "footer_text": "Generated by Title 5 Plan Reader v1.0 — © 2025 [Your Organization]",
            "colors": {
                "ok": "#00C853",
                "no": "#D50000",
                "unknown": "#9E9E9E",
                "measurement": "#1565C0",
            },
        }

    s = st.session_state["settings"]

    st.markdown("**OCR & Scale Settings**")
    s["dpi"] = st.slider("Default OCR DPI", 100, 600, int(s.get("dpi", 300)), step=50)
    s["min_text_len"] = st.number_input("Min OCR Text Length", 1, 20, int(s.get("min_text_len", 3)))

    st.markdown("**Compliance Settings**")
    s["manual_ltar"] = st.checkbox("Use manual LTAR override", value=bool(s.get("manual_ltar", False)))
    s["default_ltar"] = st.number_input(
        "Manual LTAR value (gpd/ft²)", 0.1, 2.0, float(s.get("default_ltar", 1.0)), step=0.05
    )
    s["include_thumbs"] = st.checkbox("Include ELA Thumbnails in PDF", value=bool(s.get("include_thumbs", True)))

    st.markdown("**Report Settings**")
    s["footer_text"] = st.text_input(
        "Footer Text",
        s.get("footer_text", "Generated by Title 5 Plan Reader v1.0 — © 2025 [Your Organization]"),
    )

    st.markdown("**Visualization Colors**")
    s["colors"]["ok"] = st.color_picker("OK color", s["colors"].get("ok", "#00C853"))
    s["colors"]["no"] = st.color_picker("NO color", s["colors"].get("no", "#D50000"))
    s["colors"]["unknown"] = st.color_picker("Unknown color", s["colors"].get("unknown", "#9E9E9E"))
    s["colors"]["measurement"] = st.color_picker(
        "Measurement line color", s["colors"].get("measurement", "#1565C0")
    )

    if st.button("🔄 Reset to Defaults"):
        st.session_state["settings"] = {
            "dpi": 300,
            "min_text_len": 3,
            "manual_ltar": False,
            "default_ltar": 1.0,
            "include_thumbs": True,
            "footer_text": "Generated by Title 5 Plan Reader v1.0 — © 2025 [Your Organization]",
            "colors": {
                "ok": "#00C853",
                "no": "#D50000",
                "unknown": "#9E9E9E",
                "measurement": "#1565C0",
            },
        }
        st.experimental_rerun()

# =============================================================
# Main App Tabs
# =============================================================
st.title("🏠 Title 5 Plan Reader — v1.0.2")
tab1, tab2, tab3 = st.tabs(["🏠 Home", "🧮 Compliance", "🖼️ Visualization"])

with tab1:
    st.markdown("""
    ### Welcome to the Title 5 Plan Reader
    Upload septic system plans, automatically analyze compliance, and generate visual + PDF reports.
    """)

# =============================================================
# 🧮 COMPLIANCE TAB (simplified)
# =============================================================
with tab2:
    st.subheader("🧮 Compliance Check")

    uploaded = st.file_uploader("Upload a plan image or PDF", type=["png", "jpg", "jpeg", "pdf"])
    if uploaded:
        st.success(f"Uploaded file: {uploaded.name}")

        # Placeholder compliance analysis (demo)
        st.markdown("✅ Compliance analysis completed successfully.")
        st.session_state["plan_data"] = {
            "features": [
                {"id": "tank_1", "class": "septic_tank", "bbox": [100, 300, 150, 100]},
                {"id": "leach_1", "class": "leach_field", "bbox": [400, 500, 200, 120]},
            ]
        }

# =============================================================
# 🖼️ VISUALIZATION TAB (includes Distance Tool)
# =============================================================
with tab3:
    st.subheader("🖼️ Visualization & Measurement")

    # Simulated image for demonstration
    plan_img = Image.new("RGB", (800, 600), "white")
    draw = ImageDraw.Draw(plan_img)
    draw.rectangle([100, 300, 250, 400], outline="black", width=2)
    draw.text((110, 310), "Septic Tank", fill="black")
    draw.rectangle([400, 500, 600, 620], outline="black", width=2)
    draw.text((410, 510), "Leach Field", fill="black")

    st.image(plan_img, caption="Sample Plan Image", use_container_width=True)

    # ---------------- Distance Measurement Tool ----------------
    st.markdown("---")
    st.subheader("📏 Distance Measurement Tool")

    measurement_mode = st.radio("Measurement Mode", ["Feature Snap", "Manual Click"], horizontal=True)

    ft_per_px = 0.02  # Example scale (replace with detected value)
    color = s["colors"]["measurement"]
    plan_data = st.session_state.get("plan_data", {})

    if measurement_mode == "Feature Snap":
        features = plan_data.get("features", [])
        feature_names = [f"{f['class']} ({f['id']})" for f in features]
        if len(features) < 2:
            st.warning("Need at least 2 features to measure distance.")
        else:
            f1 = st.selectbox("From feature", feature_names)
            f2 = st.selectbox("To feature", feature_names)

            if st.button("Measure Distance"):
                f1_obj = next(f for f in features if f"{f['class']} ({f['id']})" == f1)
                f2_obj = next(f for f in features if f"{f['class']} ({f['id']})" == f2)

                x1, y1, w1, h1 = f1_obj["bbox"]
                x2, y2, w2, h2 = f2_obj["bbox"]
                c1 = (x1 + w1 / 2, y1 + h1 / 2)
                c2 = (x2 + w2 / 2, y2 + h2 / 2)

                dist_px = math.sqrt((c2[0] - c1[0]) ** 2 + (c2[1] - c1[1]) ** 2)
                dist_ft = dist_px * ft_per_px

                draw.line([c1, c2], fill=color, width=3)
                draw.text(((c1[0] + c2[0]) / 2, (c1[1] + c2[1]) / 2), f"{dist_ft:.1f} ft", fill=color)

                st.image(plan_img, caption=f"Measured: {dist_ft:.1f} ft", use_container_width=True)
                st.success(f"📏 Distance = {dist_ft:.1f} ft ({f1} → {f2})")

    elif measurement_mode == "Manual Click":
        st.info("Manual click measurement mode will be added in next release.")